version: '3.8'

services: 
  
  airtel_quiz_zbm_school_api:
    container_name: airtel_quiz_zbm_school_api
    image: python:3.9
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    expose:
      - 5000
    command: >
      bash -c "pip install -r requirements.txt && python app.py"
    environment:
      - DATABASE_URL=postgresql://ussd:ussd@ussd-postgres/ussd
    networks:
      - dokploy-network

volumes:
  postgres_data:

networks:
  dokploy-network:
    external: true  # Use the previously created shared network