version: '3.8'

services: 

  airtel_quiz_zbm_school_worker:
    container_name: airtel_quiz_zbm_school_worker
    image: python:3.9
    working_dir: /app
    command: >
      bash -c "pip install -r requirements.txt && 
      celery -A worker.document_worker worker --loglevel=info"
    volumes:
      - ./:/app
      - /var/containers/volumes/prod/question-worker-ia/uploads/documents:/uploads/documents/
    environment:
      - DATABASE_URL=postgresql://ussd:ussd@ussd-postgres/ussd
      - REDIS_URL=redis://ussd-redis:6379
      - PORT=3001
      - GEMINI_API_KEY=AIzaSyAcDLEOuGQ6Pk_t1zntJWkRH4wSXFrlDb0
      - GEMINI_MODEL=gemini-2.0-flash
    networks:
      - dokploy-network

volumes:
  postgres_data:

networks:
  dokploy-network:
    external: true  # Use the previously created shared network
